In [1]:
import pandas as pd

In [2]:
url = 'https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M'
wiki = pd.read_html(url)

In [3]:
print(len(wiki))

3

In [4]:
print(wiki[0])

    Postal Code           Borough  \
0           M1A      Not assigned
1           M2A      Not assigned
2           M3A        North York
3           M4A        North York
4           M5A  Downtown Toronto
5           M6A        North York
6           M7A  Downtown Toronto
7           M8A      Not assigned
8           M9A         Etobicoke
9           M1B       Scarborough
10          M2B      Not assigned
11          M3B        North York
12          M4B         East York
13          M5B  Downtown Toronto
14          M6B        North York
15          M7B      Not assigned
16          M8B      Not assigned
17          M9B         Etobicoke
18          M1C       Scarborough
19          M2C      Not assigned
20          M3C        North York
21          M4C         East York
22          M5C  Downtown Toronto
23          M6C              York
24          M7C      Not assigned
25          M8C      Not assigned
26          M9C         Etobicoke
27          M1E       Scarborough
28          M2E      Not assigned
29          M3E      Not assigned
..          ...               ...
150         M7W      Not assigned
151         M8W         Etobicoke
152         M9W         Etobicoke
153         M1X       Scarborough
154         M2X      Not assigned
155         M3X      Not assigned
156         M4X  Downtown Toronto
157         M5X  Downtown Toronto
158         M6X      Not assigned
159         M7X      Not assigned
160         M8X         Etobicoke
161         M9X      Not assigned
162         M1Y      Not assigned
163         M2Y      Not assigned
164         M3Y      Not assigned
165         M4Y  Downtown Toronto
166         M5Y      Not assigned
167         M6Y      Not assigned
168         M7Y      East Toronto
169         M8Y         Etobicoke
170         M9Y      Not assigned
171         M1Z      Not assigned
172         M2Z      Not assigned
173         M3Z      Not assigned
174         M4Z      Not assigned
175         M5Z      Not assigned
176         M6Z      Not assigned
177         M7Z      Not assigned
178         M8Z         Etobicoke
179         M9Z      Not assigned

                                          Neighborhood
0                                                  NaN
1                                                  NaN
2                                            Parkwoods
3                                     Victoria Village
4                            Regent Park, Harbourfront
5                     Lawrence Manor, Lawrence Heights
6          Queen's Park, Ontario Provincial Government
7                                                  NaN
8              Islington Avenue, Humber Valley Village
9                                       Malvern, Rouge
10                                                 NaN
11                                           Don Mills
12                     Parkview Hill, Woodbine Gardens
13                            Garden District, Ryerson
14                                           Glencairn
15                                                 NaN
16                                                 NaN
17   West Deane Park, Princess Gardens, Martin Grov...
18              Rouge Hill, Port Union, Highland Creek
19                                                 NaN
20                                           Don Mills
21                                    Woodbine Heights
22                                      St. James Town
23                                  Humewood-Cedarvale
24                                                 NaN
25                                                 NaN
26   Eringate, Bloordale Gardens, Old Burnhamthorpe...
27                   Guildwood, Morningside, West Hill
28                                                 NaN
29                                                 NaN
..                                                 ...
150                                                NaN
151                             Alderwood, Long Branch
152                Northwest, West Humber - Clairville
153                                        Upper Rouge
154                                                NaN
155                                                NaN
156                        St. James Town, Cabbagetown
157             First Canadian Place, Underground city
158                                                NaN
159                                                NaN
160      The Kingsway, Montgomery Road, Old Mill North
161                                                NaN
162                                                NaN
163                                                NaN
164                                                NaN
165                               Church and Wellesley
166                                                NaN
167                                                NaN
168  Business reply mail Processing Centre, South C...
169  Old Mill South, King's Mill Park, Sunnylea, Hu...
170                                                NaN
171                                                NaN
172                                                NaN
173                                                NaN
174                                                NaN
175                                                NaN
176                                                NaN
177                                                NaN
178  Mimico NW, The Queensway West, South of Bloor,...
179                                                NaN

[180 rows x 3 columns]

### The dataframe will consist of three columns: PostalCode, Borough, and Neighborhood

In [5]:
postal_codes = wiki[0]

In [6]:
postal_codes.columns

Index(['Postal Code', 'Borough', 'Neighborhood'], dtype='object')

In [7]:
postal_codes.shape

(180, 3)

In [8]:
print(postal_codes.loc[1])

Postal Code              M2A
Borough         Not assigned
Neighborhood             NaN
Name: 1, dtype: object

In [9]:
postal_codes.head()

  Postal Code           Borough               Neighborhood
0         M1A      Not assigned                        NaN
1         M2A      Not assigned                        NaN
2         M3A        North York                  Parkwoods
3         M4A        North York           Victoria Village
4         M5A  Downtown Toronto  Regent Park, Harbourfront

### Only process the cells that have an assigned borough. Ignore cells with a borough that is Not assigned.

In [10]:
df = postal_codes.drop(postal_codes[postal_codes.Borough == 'Not assigned'].index)

In [14]:
df.head(5)

  Postal Code           Borough                                 Neighborhood
2         M3A        North York                                    Parkwoods
3         M4A        North York                             Victoria Village
4         M5A  Downtown Toronto                    Regent Park, Harbourfront
5         M6A        North York             Lawrence Manor, Lawrence Heights
6         M7A  Downtown Toronto  Queen's Park, Ontario Provincial Government

In [32]:
df.columns

Index(['Postal Code', 'Borough', 'Neighborhood'], dtype='object')

In [36]:
unique = df.groupby('Postal Code').nunique()

In [37]:
unique

             Postal Code  Borough  Neighborhood
Postal Code
M1B                    1        1             1
M1C                    1        1             1
M1E                    1        1             1
M1G                    1        1             1
M1H                    1        1             1
M1J                    1        1             1
M1K                    1        1             1
M1L                    1        1             1
M1M                    1        1             1
M1N                    1        1             1
M1P                    1        1             1
M1R                    1        1             1
M1S                    1        1             1
M1T                    1        1             1
M1V                    1        1             1
M1W                    1        1             1
M1X                    1        1             1
M2H                    1        1             1
M2J                    1        1             1
M2K                    1        1             1
M2L                    1        1             1
M2M                    1        1             1
M2N                    1        1             1
M2P                    1        1             1
M2R                    1        1             1
M3A                    1        1             1
M3B                    1        1             1
M3C                    1        1             1
M3H                    1        1             1
M3J                    1        1             1
...                  ...      ...           ...
M6C                    1        1             1
M6E                    1        1             1
M6G                    1        1             1
M6H                    1        1             1
M6J                    1        1             1
M6K                    1        1             1
M6L                    1        1             1
M6M                    1        1             1
M6N                    1        1             1
M6P                    1        1             1
M6R                    1        1             1
M6S                    1        1             1
M7A                    1        1             1
M7R                    1        1             1
M7Y                    1        1             1
M8V                    1        1             1
M8W                    1        1             1
M8X                    1        1             1
M8Y                    1        1             1
M8Z                    1        1             1
M9A                    1        1             1
M9B                    1        1             1
M9C                    1        1             1
M9L                    1        1             1
M9M                    1        1             1
M9N                    1        1             1
M9P                    1        1             1
M9R                    1        1             1
M9V                    1        1             1
M9W                    1        1             1

[103 rows x 3 columns]

### If a cell has a borough but a Not assigned neighborhood, then the neighborhood will be the same as the borough.

In [44]:
"Not assigned" in df['Neighborhood'].values

False

### In the last cell of your notebook, use the .shape method to print the number of rows of your dataframe.

In [46]:
df.shape

(103, 3)