In [1]:
import pandas as pd

In [2]:
url = 'https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M'
wiki = pd.read_html(url)

In [3]:
print(len(wiki))

3

In [4]:
print(wiki[0])

    Postal Code           Borough  \
0           M1A      Not assigned
1           M2A      Not assigned
2           M3A        North York
3           M4A        North York
4           M5A  Downtown Toronto
5           M6A        North York
6           M7A  Downtown Toronto
7           M8A      Not assigned
8           M9A         Etobicoke
9           M1B       Scarborough
10          M2B      Not assigned
11          M3B        North York
12          M4B         East York
13          M5B  Downtown Toronto
14          M6B        North York
15          M7B      Not assigned
16          M8B      Not assigned
17          M9B         Etobicoke
18          M1C       Scarborough
19          M2C      Not assigned
20          M3C        North York
21          M4C         East York
22          M5C  Downtown Toronto
23          M6C              York
24          M7C      Not assigned
25          M8C      Not assigned
26          M9C         Etobicoke
27          M1E       Scarborough
28          M2E      Not assigned
29          M3E      Not assigned
..          ...               ...
150         M7W      Not assigned
151         M8W         Etobicoke
152         M9W         Etobicoke
153         M1X       Scarborough
154         M2X      Not assigned
155         M3X      Not assigned
156         M4X  Downtown Toronto
157         M5X  Downtown Toronto
158         M6X      Not assigned
159         M7X      Not assigned
160         M8X         Etobicoke
161         M9X      Not assigned
162         M1Y      Not assigned
163         M2Y      Not assigned
164         M3Y      Not assigned
165         M4Y  Downtown Toronto
166         M5Y      Not assigned
167         M6Y      Not assigned
168         M7Y      East Toronto
169         M8Y         Etobicoke
170         M9Y      Not assigned
171         M1Z      Not assigned
172         M2Z      Not assigned
173         M3Z      Not assigned
174         M4Z      Not assigned
175         M5Z      Not assigned
176         M6Z      Not assigned
177         M7Z      Not assigned
178         M8Z         Etobicoke
179         M9Z      Not assigned

                                          Neighborhood
0                                                  NaN
1                                                  NaN
2                                            Parkwoods
3                                     Victoria Village
4                            Regent Park, Harbourfront
5                     Lawrence Manor, Lawrence Heights
6          Queen's Park, Ontario Provincial Government
7                                                  NaN
8              Islington Avenue, Humber Valley Village
9                                       Malvern, Rouge
10                                                 NaN
11                                           Don Mills
12                     Parkview Hill, Woodbine Gardens
13                            Garden District, Ryerson
14                                           Glencairn
15                                                 NaN
16                                                 NaN
17   West Deane Park, Princess Gardens, Martin Grov...
18              Rouge Hill, Port Union, Highland Creek
19                                                 NaN
20                                           Don Mills
21                                    Woodbine Heights
22                                      St. James Town
23                                  Humewood-Cedarvale
24                                                 NaN
25                                                 NaN
26   Eringate, Bloordale Gardens, Old Burnhamthorpe...
27                   Guildwood, Morningside, West Hill
28                                                 NaN
29                                                 NaN
..                                                 ...
150                                                NaN
151                             Alderwood, Long Branch
152                Northwest, West Humber - Clairville
153                                        Upper Rouge
154                                                NaN
155                                                NaN
156                        St. James Town, Cabbagetown
157             First Canadian Place, Underground city
158                                                NaN
159                                                NaN
160      The Kingsway, Montgomery Road, Old Mill North
161                                                NaN
162                                                NaN
163                                                NaN
164                                                NaN
165                               Church and Wellesley
166                                                NaN
167                                                NaN
168  Business reply mail Processing Centre, South C...
169  Old Mill South, King's Mill Park, Sunnylea, Hu...
170                                                NaN
171                                                NaN
172                                                NaN
173                                                NaN
174                                                NaN
175                                                NaN
176                                                NaN
177                                                NaN
178  Mimico NW, The Queensway West, South of Bloor,...
179                                                NaN

[180 rows x 3 columns]

### The dataframe will consist of three columns: PostalCode, Borough, and Neighborhood

In [5]:
postal_codes = wiki[0]

In [6]:
postal_codes.columns

Index(['Postal Code', 'Borough', 'Neighborhood'], dtype='object')

In [7]:
postal_codes.shape

(180, 3)

In [8]:
print(postal_codes.loc[1])

Postal Code              M2A
Borough         Not assigned
Neighborhood             NaN
Name: 1, dtype: object

In [9]:
postal_codes.head()

  Postal Code           Borough               Neighborhood
0         M1A      Not assigned                        NaN
1         M2A      Not assigned                        NaN
2         M3A        North York                  Parkwoods
3         M4A        North York           Victoria Village
4         M5A  Downtown Toronto  Regent Park, Harbourfront

### Only process the cells that have an assigned borough. Ignore cells with a borough that is Not assigned.

In [10]:
df = postal_codes.drop(postal_codes[postal_codes.Borough == 'Not assigned'].index)

In [14]:
df.head(5)

  Postal Code           Borough                                 Neighborhood
2         M3A        North York                                    Parkwoods
3         M4A        North York                             Victoria Village
4         M5A  Downtown Toronto                    Regent Park, Harbourfront
5         M6A        North York             Lawrence Manor, Lawrence Heights
6         M7A  Downtown Toronto  Queen's Park, Ontario Provincial Government

In [32]:
df.columns

Index(['Postal Code', 'Borough', 'Neighborhood'], dtype='object')

In [36]:
unique = df.groupby('Postal Code').nunique()

In [37]:
unique

             Postal Code  Borough  Neighborhood
Postal Code
M1B                    1        1             1
M1C                    1        1             1
M1E                    1        1             1
M1G                    1        1             1
M1H                    1        1             1
M1J                    1        1             1
M1K                    1        1             1
M1L                    1        1             1
M1M                    1        1             1
M1N                    1        1             1
M1P                    1        1             1
M1R                    1        1             1
M1S                    1        1             1
M1T                    1        1             1
M1V                    1        1             1
M1W                    1        1             1
M1X                    1        1             1
M2H                    1        1             1
M2J                    1        1             1
M2K                    1        1             1
M2L                    1        1             1
M2M                    1        1             1
M2N                    1        1             1
M2P                    1        1             1
M2R                    1        1             1
M3A                    1        1             1
M3B                    1        1             1
M3C                    1        1             1
M3H                    1        1             1
M3J                    1        1             1
...                  ...      ...           ...
M6C                    1        1             1
M6E                    1        1             1
M6G                    1        1             1
M6H                    1        1             1
M6J                    1        1             1
M6K                    1        1             1
M6L                    1        1             1
M6M                    1        1             1
M6N                    1        1             1
M6P                    1        1             1
M6R                    1        1             1
M6S                    1        1             1
M7A                    1        1             1
M7R                    1        1             1
M7Y                    1        1             1
M8V                    1        1             1
M8W                    1        1             1
M8X                    1        1             1
M8Y                    1        1             1
M8Z                    1        1             1
M9A                    1        1             1
M9B                    1        1             1
M9C                    1        1             1
M9L                    1        1             1
M9M                    1        1             1
M9N                    1        1             1
M9P                    1        1             1
M9R                    1        1             1
M9V                    1        1             1
M9W                    1        1             1

[103 rows x 3 columns]

### If a cell has a borough but a Not assigned neighborhood, then the neighborhood will be the same as the borough.

In [44]:
"Not assigned" in df['Neighborhood'].values

False

### In the last cell of your notebook, use the .shape method to print the number of rows of your dataframe.

In [46]:
df.shape

(103, 3)

In [47]:
geo = pd.read_csv('Geospatial_Coordinates.csv')

In [48]:
geo

    Postal Code   Latitude  Longitude
0           M1B  43.806686 -79.194353
1           M1C  43.784535 -79.160497
2           M1E  43.763573 -79.188711
3           M1G  43.770992 -79.216917
4           M1H  43.773136 -79.239476
5           M1J  43.744734 -79.239476
6           M1K  43.727929 -79.262029
7           M1L  43.711112 -79.284577
8           M1M  43.716316 -79.239476
9           M1N  43.692657 -79.264848
10          M1P  43.757410 -79.273304
11          M1R  43.750072 -79.295849
12          M1S  43.794200 -79.262029
13          M1T  43.781638 -79.304302
14          M1V  43.815252 -79.284577
15          M1W  43.799525 -79.318389
16          M1X  43.836125 -79.205636
17          M2H  43.803762 -79.363452
18          M2J  43.778517 -79.346556
19          M2K  43.786947 -79.385975
20          M2L  43.757490 -79.374714
21          M2M  43.789053 -79.408493
22          M2N  43.770120 -79.408493
23          M2P  43.752758 -79.400049
24          M2R  43.782736 -79.442259
25          M3A  43.753259 -79.329656
26          M3B  43.745906 -79.352188
27          M3C  43.725900 -79.340923
28          M3H  43.754328 -79.442259
29          M3J  43.767980 -79.487262
..          ...        ...        ...
73          M6C  43.693781 -79.428191
74          M6E  43.689026 -79.453512
75          M6G  43.669542 -79.422564
76          M6H  43.669005 -79.442259
77          M6J  43.647927 -79.419750
78          M6K  43.636847 -79.428191
79          M6L  43.713756 -79.490074
80          M6M  43.691116 -79.476013
81          M6N  43.673185 -79.487262
82          M6P  43.661608 -79.464763
83          M6R  43.648960 -79.456325
84          M6S  43.651571 -79.484450
85          M7A  43.662301 -79.389494
86          M7R  43.636966 -79.615819
87          M7Y  43.662744 -79.321558
88          M8V  43.605647 -79.501321
89          M8W  43.602414 -79.543484
90          M8X  43.653654 -79.506944
91          M8Y  43.636258 -79.498509
92          M8Z  43.628841 -79.520999
93          M9A  43.667856 -79.532242
94          M9B  43.650943 -79.554724
95          M9C  43.643515 -79.577201
96          M9L  43.756303 -79.565963
97          M9M  43.724766 -79.532242
98          M9N  43.706876 -79.518188
99          M9P  43.696319 -79.532242
100         M9R  43.688905 -79.554724
101         M9V  43.739416 -79.588437
102         M9W  43.706748 -79.594054

[103 rows x 3 columns]

In [50]:
result_df = pd.merge(df, geo)

In [53]:
result_df.head(10)

,Postal Code,Borough,Neighborhood,Latitude,Longitude
0,M3A,North York,Parkwoods,43.753259,-79.329656
1,M4A,North York,Victoria Village,43.725882,-79.315572
2,M5A,Downtown Toronto,"Regent Park, Harbourfront",43.654260,-79.360636
3,M6A,North York,"Lawrence Manor, Lawrence Heights",43.718518,-79.464763
4,M7A,Downtown Toronto,"Queen's Park, Ontario Provincial Government",43.662301,-79.389494
5,M9A,Etobicoke,"Islington Avenue, Humber Valley Village",43.667856,-79.532242
6,M1B,Scarborough,"Malvern, Rouge",43.806686,-79.194353
7,M3B,North York,Don Mills,43.745906,-79.352188
8,M4B,East York,"Parkview Hill, Woodbine Gardens",43.706397,-79.309937
9,M5B,Downtown Toronto,"Garden District, Ryerson",43.657162,-79.378937